// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface PokemonResponse {
    count:    number;
    next:     string | null;
    previous: string | null;
    results:  Pokemon[];
}

export interface Pokemon {
    name: string;
    url:  string;
}
